<?php 
    include("config/config.php");

    function generateUniqueId($maxlen = 8) {
        // Use uniqid to generate a unique ID based on the current time in microseconds
        $uniqueId = uniqid();
    
        // Remove the "0." prefix from the unique ID generated by uniqid
        $uniqueId = substr($uniqueId, 2);
    
        // Add additional randomness using mt_rand and md5
        $randomBytes = md5(mt_rand(), true);
        $randomHex = bin2hex($randomBytes);
    
        // Combine the unique ID and random values
        $combinedId = $uniqueId . $randomHex;
    
        // Take the first 8 characters to get the desired length
        $result = substr($combinedId, 0, $maxlen);
    
        return $result;
    }
    function generateRoomID() {
        global $conn;

        do {
            $room_id = generateUniqueId(8);
            $chk_sql = mysqli_query($conn, "SELECT id FROM battle_rooms WHERE id = '$room_id'");
        } while(mysqli_num_rows($chk_sql) > 0);

        return $room_id;
    }
    function createRoom($num_ques = 10, $topic, $num_players = 5, $time_per_ques = 60, $schedule){
        global $conn;
        $room_id = generateRoomID();
        $currentDateTime = date("Y-m-d H:i:s");

        $sql = mysqli_query($conn, "INSERT INTO battle_rooms (id, num_ques, topic, num_players, time_per_ques, room_owner, started, completed, scheduled_on, created_at)
                                    VALUES ('$room_id', $num_ques, '$topic', $num_players, $time_per_ques, '". $_SESSION['id'] ."', 0, 0, '$schedule', '$currentDateTime')");

        if($sql) {
            generateRoomQuestions($room_id);
            return $room_id;
        } else {
            return null;
        }
    }

    function joinRoom($room_id) {
        global $conn;
        
        if(!doesRoomExist($room_id)) {
            return array(
                "status" => "Error",
                "msg" => "Room does not exist"
            );
        }

        if(hasRoomExpired($room_id)) {
            return array(
                "status" => "Error",
                "msg" => "Room has already expired"
            );
        }

        if(hasRoomStartedOrCompleted($room_id)) {
            return array(
                "status" => "Error",
                "msg" => "Room cannot be accessed now"
            );
        }

        if(isRoomFull($room_id)) {
            return array(
                "status" => "Error",
                "msg" => "Room capacity full"
            );
        }

        if(hasPlayerAlreadyLeft($room_id, $_SESSION['id'])) {
            return array(
                "status" => "Error",
                "msg" => "Player cannot enter the room again"
            );
        }

        $sql_chk = mysqli_query($conn, "SELECT * FROM battle_room_players WHERE room_id = '$room_id' AND user_id = '". $_SESSION['id'] ."'");
        $res_chk = mysqli_fetch_assoc($sql_chk);

        if($res_chk) {
            $sql = mysqli_query($conn, "UPDATE battle_room_players SET left_room = 0 WHERE room_id = '$room_id' AND user_id = '". $_SESSION['id'] ."'");
        } else {
            $sql = mysqli_query($conn, "INSERT INTO battle_room_players (room_id, user_id, score, started, completed, left_room) VALUES ('$room_id', '". $_SESSION['id'] ."', 0, 0, 0, 0)");
        }

        if($sql) {

            $_SESSION['live_room'] = $room_id;

            return array(
                "status" => "success",
                "msg" => "Successfully Joined"
            );
        } else {
            return array(
                "status" => "Error",
                "msg" => "Error joining the room"
            );
        }
    }

    function generateRoomQuestions($room_id) {
        global $conn;

        $sessionsql = mysqli_query($conn, "SELECT class FROM users WHERE id='".$_SESSION['id']."'");
        $sessionrow = mysqli_fetch_assoc($sessionsql);

        $sql_room = mysqli_query($conn, "SELECT num_ques, time_per_ques, scheduled_on, topic FROM battle_rooms WHERE id = '$room_id'");
        $res_room = mysqli_fetch_assoc($sql_room);

        $sql_part = "";

        if($res_room['topic'] !== 'All') {
            $sql_part = 'AND topic = "'. $res_room['topic'] . '" ';
        }

        $sql_ques = mysqli_query($conn, "SELECT id FROM count_quest 
                                        WHERE class = '". $sessionrow['class'] . "' 
                                        $sql_part 
                                        AND status = 1
                                        ORDER BY RAND()
                                        LIMIT ". $res_room['num_ques'] . "");


                
        $startTime = $res_room['scheduled_on'];
        while($res_ques = mysqli_fetch_assoc($sql_ques)) {
            $endTime = date('Y-m-d H:i:s', strtotime($startTime) + $res_room['time_per_ques']);
            if(mysqli_query($conn, "INSERT INTO battle_room_questions (room_id, ques_id, start_time, end_time) VALUES ('$room_id', '". $res_ques['id'] ."', '$startTime', '$endTime')")) {
                $startTime = $endTime;
            } else {
                die($conn->error);
            }
        }
    }

    function leaveRoom($room_id) {
        global $conn;

        $user_id = $_SESSION['id'];
        if(mysqli_query($conn, "UPDATE battle_room_players SET left_room = 1 WHERE room_id = '$room_id' AND user_id = '$user_id'")) {
            unset($_SESSION['live_room']);
        }
    }

    function getWaitingPlayers($room_id) {
        global $conn;

        $sql = mysqli_query($conn, "SELECT u.id, u.fullname, u.avatar, sc.name AS class, sm.name AS school
                                    FROM battle_room_players brp
                                    JOIN users u
                                    ON brp.user_id = u.id
                                    JOIN subject_class sc
                                    ON u.class = sc.id
                                    JOIN school_management sm
                                    ON u.school = sm.id
                                    WHERE brp.room_id = '$room_id'
                                    AND left_room = 0
                                    AND started = 0
                                    AND completed = 0");
        
        $res_arr = array();
        while($row = mysqli_fetch_assoc($sql)) {
            $res_arr[] = $row;
        }

        return $res_arr;
    }
    function doesRoomExist($room_id) {
        global $conn;

        $sql = mysqli_query($conn, "SELECT * FROM battle_rooms WHERE id = '$room_id'");
        $res = mysqli_fetch_assoc($sql);

        if($res) {
            return true;
        } else {
            return false;
        }
    }

    function hasPlayerAlreadyLeft($room_id, $user_id) {
        global $conn;

        $sql = mysqli_query($conn, "SELECT left_room 
                                    FROM battle_room_players 
                                    WHERE room_id = '$room_id' 
                                    AND user_id = '$user_id' 
                                    AND started = 1");

        $res = mysqli_fetch_assoc($sql);

        if($res && $res['left_room'] == 1) {
            return true;
        } else {
            return false;
        }
    }

    function hasRoomStartedOrCompleted($room_id) {
        global $conn;
        $sql = mysqli_query($conn, "SELECT started, completed FROM battle_rooms WHERE id = '$room_id'");
        $res = mysqli_fetch_assoc($sql);

        if($res['started'] == 1 || $res['completed'] == 1) {
            return true;
        } else {
             return false;
        }
    }

    function isRoomFull($room_id) {
        global $conn;
        $sql = mysqli_query($conn, "SELECT COUNT(*) AS num_players FROM battle_room_players WHERE room_id = '$room_id' AND left_room = 0 AND started = 0 AND completed = 0");
        $res = mysqli_fetch_assoc($sql);

        $sql_max = mysqli_query($conn, "SELECT num_players FROM battle_rooms WHERE id = '$room_id'");
        $res_max = mysqli_fetch_assoc($sql_max);

        if($res && $res_max['num_players'] <= $res['num_players']) {
            return true;
        } else {
            return false;
        }
    }

    function hasRoomExpired($room_id) {
        global $conn;
        $currentDateTime = new DateTime();

        $sql = mysqli_query($conn, "SELECT scheduled_on FROM battle_rooms WHERE id = '$room_id'");
        $res = mysqli_fetch_assoc($sql);

        $scheduledDateTime = new DateTime($res['scheduled_on']);
        $interval = $currentDateTime->diff($scheduledDateTime);

        if($interval->invert) {
            return true;
        } else {
            false;
        }
    }

    function checkProperPlayer($room_id, $user_id) {
        global $conn;

        $sql = mysqli_query($conn, "SELECT * FROM battle_room_players
                                    WHERE room_id = '$room_id' 
                                    AND user_id = '$user_id'
                                    AND completed = 0
                                    AND left_room = 0");

        if(mysqli_num_rows($sql) > 0) {
            return true;
        } else {
            return false;
        }
    }

    function getNextQuestion($room_id) {
        global $conn;

        $currentTime = date('Y-m-d H:i:s');

        $sql = mysqli_query($conn, "SELECT brp.ques_id 
                                    FROM battle_room_questions brp
                                    WHERE brp.room_id = '$room_id'
                                    AND brp.start_time <= '$currentTime'
                                    AND brp.end_time >= '$currentTime'");

        if(mysqli_num_rows($sql) > 0) {
            $res = mysqli_fetch_assoc($sql);

            return $res['ques_id'];
        } else {
            return 0;
        }
    }
?>