INSERT INTO vocab_context_table (id, content, meaning, example, context_id) VALUES
(120, 'Lumos', 'Creates light at the tip of the wand.', NULL, 2),
(121, 'Accio', 'Summons an object to the caster.', NULL, 2),
(122, 'Wingardium Leviosa', 'Levitates objects.', NULL, 2),
(123, 'Alohomora', 'Opens locked doors and objects.', NULL, 2),
(124, 'Expelliarmus', 'Disarms the opponent, causing their wand to fly out of their hand.', NULL, 2),
(125, 'Avada Kedavra', 'The Killing Curse; causes instant death to the target.', NULL, 2),
(126, 'Expecto Patronum', 'Conjures a Patronus, a powerful positive energy projection that repels Dementors.', NULL, 2),
(127, 'Protego', 'Creates a protective shield that defends against spells.', NULL, 2),
(128, 'Petrificus Totalus', 'Temporarily freezes and immobilizes the target.', NULL, 2),
(129, 'Stupefy', 'Stuns and temporarily incapacitates the target.', NULL, 2),
(130, 'Obliviate', 'Erases or modifies the memories of the target.', NULL, 2),
(131, 'Riddikulus', 'Transforms a Boggart into something funny, thereby neutralizing its fear.', NULL, 2),
(132, 'Imperio', 'Controls the actions and thoughts of the target, essentially putting them under the casters control.', NULL, 2),
(133, 'Sectumsempra', 'Dark curse; causes deep, slashing wounds on the target.', NULL, 2),
(134, 'Crucio', 'Torture Curse; inflicts immense pain on the target.', NULL, 2),
(135, 'Reducto', 'Blasting Curse; causes the target to explode or be blasted apart.', NULL, 2),
(136, 'Episkey', 'Healing spell; used to heal minor injuries.', NULL, 2),
(137, 'Incendio', 'Fire-Making Charm; conjures flames.', NULL, 2),
(138, 'Aguamenti', 'Water-Making Charm; conjures water from the tip of the wand.', NULL, 2),
(139, 'Muffliato', 'Creates a buzzing noise in the ears of anyone nearby, preventing them from eavesdropping on conversations.', NULL, 2),
(140, 'Engorgio', 'Engorgement Charm; causes the target to swell or enlarge.', NULL, 2),
(141, 'Colloportus', 'Locking Charm; magically locks a door or object.', NULL, 2),
(142, 'Sonorus', 'Amplifies the users voice, making it louder and carry over long distances.', NULL, 2),
(143, 'Finite Incantatem', 'Stops the effects of spells or enchantments.', NULL, 2),
(144, 'Reparo', 'Mending Charm; used to repair broken objects.', NULL, 2),
(145, 'Bombarda', 'Exploding Charm; causes an object to explode or burst open.', NULL, 2),
(146, 'Silencio', 'Silencing Charm; silences the target, preventing them from making any sound.', NULL, 2);

INSERT INTO vocab_context_table (id, content, meaning, example, context_id) VALUES
(147, 'Apparition', 'Advanced magical transportation; allows wizards to instantly appear or disappear to a desired location.', NULL, 2),
(148, 'Evanesco', 'Vanishing Charm; causes an object to disappear.', NULL, 2),
(149, 'Lumos Maxima', 'Creates a strong burst of light, illuminating a wide area.', NULL, 2),
(150, 'Protean Charm', 'Allows communication between objects of the same kind.', NULL, 2),
(151, 'Levicorpus', 'Inversion spell; causes the target to be suspended upside down by their ankle.', NULL, 2),
(152, 'Desperatio', 'Creates a cloud of dark smoke, providing cover or distraction.', NULL, 2),
(153, 'Descendo', 'Causes the target to move downward or descend rapidly.', NULL, 2),
(154, 'Langlock', 'Glues the targets tongue to the roof of their mouth, temporarily preventing them from speaking.', NULL, 2),
(155, 'Confundo', 'Confusion Charm; causes the target to become confused and disoriented.', NULL, 2),
(156, 'Bombarda Maxima', 'Enhanced version of the Bombarda spell; causes a more powerful explosion.', NULL, 2),
(157, 'Ventus', 'Produces a gust of wind or creates air currents.', NULL, 2),
(158, 'Aparecium', 'Revealing Charm; makes invisible ink or hidden markings visible.', NULL, 2),
(159, 'Enervate', 'Revives a person who has been knocked unconscious.', NULL, 2),
(160, 'Salvio Hexia', 'Protection Charm used to safeguard against hexes.', NULL, 2),
(161, 'Homorphus', 'Transforms a werewolf into its human form.', NULL, 2),
(162, 'Orchideous', 'Conjures a bouquet of flowers from the tip of the wand.', NULL, 2),
(163, 'Tarantallegra', 'Forces the targets legs to dance uncontrollably.', NULL, 2),
(164, 'Glisseo', 'Transforms a staircase into a slide, allowing for rapid descent or ascent.', NULL, 2),
(165, 'Epoximise', 'Glues objects together.', NULL, 2),
(166, 'Brackium Emendo', 'Heals broken bones.', NULL, 2),
(167, 'Dissendium', 'Reveals hidden passageways or doors.', NULL, 2),
(168, 'Vulnera Sanentur', 'Healing spell used to heal severe wounds.', NULL, 2),
(169, 'Fianto Duri', 'Creates a protective barrier or shield.', NULL, 2);

INSERT INTO vocab_context_table (id, content, meaning, example, context_id) VALUES
(170, 'Rennervate', 'Revives a person or creature who has been knocked unconscious.', NULL, 2),
(171, 'Avis', 'Conjures a flock of birds from the tip of the wand.', NULL, 2),
(174, 'Impedimenta', 'Impediment Jinx; slows down or immobilizes the target.', NULL, 2),
(175, 'Legilimens', 'Allows the caster to delve into the mind of the target and extract thoughts or memories.', NULL, 2),
(176, 'Protego Totalum', 'Creates a protective barrier that shields an area or location.', NULL, 2),
(177, 'Revelio', 'Revealing Charm; reveals hidden objects or concealed magical beings.', NULL, 2),
(178, 'Diffindo', 'Severing Charm; causes the target to be cut or split open.', NULL, 2),
(179, 'Flagrate', 'Allows the caster to write or draw in the air with fire, leaving a burning trail.', NULL, 2),
(180, 'Aqua Eructo', 'Produces a jet of water from the wand.', NULL, 2),
(181, 'Liberacorpus', 'Counter-spell for Levicorpus; releases the target from being suspended upside down.', NULL, 2),
(182, 'Mobiliarbus', 'Moves or levitates a tree or plant.', NULL, 2),
(183, 'Expulso', 'Causes an object to explode or be blasted apart.', NULL, 2),
(185, 'Arania Exumai', 'Spider Repelling Spell; repels or blasts away spiders.', NULL, 2),
(186, 'Quietus', 'Counter-spell for Sonorus; lowers the volume of the caster''s voice.', NULL, 2),
(188, 'Locomotor', 'Moves or levitates an object.', NULL, 2),
(189, 'Periculum', 'Produces red sparks or flares as a distress signal.', NULL, 2),
(190, 'Deletrius', 'Counter-spell for Prior Incantato; erases the effects of the previously cast spell on an object.', NULL, 2);

